apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
        aadpodidbinding: trading
    spec:
      containers:
        - name: trading
          image: jeevplayeconomy.azurecr.io/play.trading:1.0.2
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: jeevplayeconomy
            - name: ServiceSettings__Authority
              value: https://jeevplayeconomy.eastus.cloudapp.azure.com/identity-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5006
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5006
            initialDelaySeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
    - port: 80
      targetPort: 5006
